name: Build and Push Docker Image

on:
  workflow_call: 
    inputs:
      image_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker BuildKit
        uses: docker/setup-buildx-action@v3.3.0

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/${{ github.repository }}/${{ inputs.image_name }}
          tags: type=ref,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: |
            ${{ inputs.image_name }}/
          file: |
            ${{ inputs.image_name }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max